# Generated by Django 6.0.7 on 2026-07-27 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_discount_remove_category_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='category',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
