# Generated by Django 6.0.7 on 2026-07-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_offer_active',
            field=models.BooleanField(default=True),
        ),
    ]
