# Generated by Django 6.0.7 on 2026-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('target_url', models.CharField(default='/shop/', help_text='Redirect path e.g. /shop/, /shop/?category=Guitars', max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('display_mode', models.CharField(choices=[('HERO_SLIDER', 'Hero Slider / Carousel'), ('SPLIT_SCREEN', 'Split Screen Promo'), ('PROMO_STRIP', 'Top Promotional Strip'), ('CATEGORY_HERO', 'Category Banner')], default='SPLIT_SCREEN', max_length=30)),
                ('priority', models.IntegerField(default=1, help_text='Order priority (01, 02, etc.)')),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published / Live'), ('DRAFT', 'Draft'), ('STAGED', 'Staged / Scheduled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('impressions_count', models.PositiveIntegerField(default=0)),
                ('clicks_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
