# Generated by Django 6.0.7 on 2026-09-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='display_mode',
            field=models.CharField(choices=[('HERO_SLIDER', 'Hero Slider / Carousel'), ('PROMO_STRIP', 'Top Promotional Strip')], default='HERO_SLIDER', max_length=30),
        ),
    ]
