# Generated by Django 6.0.7 on 2026-09-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_banners', '0002_alter_banner_display_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'Published / Live'), ('DRAFT', 'Draft / Inactive')], default='DRAFT', max_length=20),
        ),
    ]
