# Generated by Django 6.0.7 on 2026-09-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_banners', '0003_alter_banner_status'),
        ('products', '0010_productvariant_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('HERO_LEFT', 'Hero Left Banner (Top Seller)'), ('HERO_RIGHT', 'Hero Right Banner (Featured Flagship)'), ('GRID_SPOTLIGHT', 'In-Grid Spotlight (Premium Specs)')], max_length=30, unique=True)),
                ('badge_text', models.CharField(default='TOP SELLER', max_length=50)),
                ('custom_title', models.CharField(blank=True, help_text='Custom display title (defaults to product name if blank)', max_length=150, null=True)),
                ('subtitle', models.CharField(blank=True, help_text='Series name or short promotional description', max_length=200, null=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Custom dark backdrop image', null=True, upload_to='showcases/')),
                ('button_label', models.CharField(default='SHOP MODEL', max_length=50)),
                ('spec_1_label', models.CharField(blank=True, default='Wattage', max_length=50)),
                ('spec_1_value', models.CharField(blank=True, default='30 Watts RMS', max_length=50)),
                ('spec_2_label', models.CharField(blank=True, default='Speakers', max_length=50)),
                ('spec_2_value', models.CharField(blank=True, default='2 X 12" Celestion', max_length=50)),
                ('spec_3_label', models.CharField(blank=True, default='Valves', max_length=50)),
                ('spec_3_value', models.CharField(blank=True, default='4 X EL84', max_length=50)),
                ('spec_4_label', models.CharField(blank=True, default='Inputs', max_length=50)),
                ('spec_4_value', models.CharField(blank=True, default='Normal & Top Boost', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showcases', to='products.product')),
            ],
            options={
                'verbose_name': 'Shop Showcase',
                'verbose_name_plural': 'Shop Showcases',
            },
        ),
    ]
