# Generated by Django 6.0.7 on 2026-09-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_banners', '0004_shopshowcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopshowcase',
            name='slot',
            field=models.CharField(choices=[('HERO_LEFT', 'Hero Left Banner (Top Seller)'), ('HERO_RIGHT', 'Hero Right Banner (Featured Flagship)'), ('GRID_SPOTLIGHT', 'In-Grid Spotlight (Premium Specs)'), ('SIDEBAR_PROMO', 'Sidebar Special Offer (Filter Drawer)')], max_length=30, unique=True),
        ),
    ]
