# Generated by Django 6.0.7 on 2026-09-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0019_remove_referral_referred_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_images', to='orders.orderitem')),
            ],
            options={
                'db_table': 'orders_returnrequestimage',
            },
        ),
    ]
