# Generated by Django 5.2.4 on 2026-06-10 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpverification_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otpverification',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
