# Generated by Django 6.0.7 on 2026-09-11 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Percentage discount between 1% and 99%', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('start_date', models.DateField(blank=True, help_text='Offer start date (optional)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Offer expiry date (optional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Offer',
                'verbose_name_plural': 'Product Offers',
                'ordering': ['-created_at'],
            },
        ),
    ]
