# Generated by Django 6.0.7 on 2026-08-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_PICKUP', 'Item Picked Up'), ('RETURNED', 'Returned'), ('REFUNDED', 'Refunded')], default='CONFIRMED', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_PICKUP', 'Item Picked Up'), ('RETURNED', 'Returned'), ('REFUNDED', 'Refunded')], default='CONFIRMED', max_length=50),
        ),
    ]
