# Generated by Django 6.0.7 on 2026-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='expected_pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
