# Generated by Django 6.0.7 on 2026-08-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_order_status_alter_orderitem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gateway_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
