# Generated by Django 6.0.7 on 2026-08-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_gateway_order_id_order_gateway_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gateway_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gateway_payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gateway_signature',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
