# Generated by Django 6.0.7 on 2026-08-28 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_cancel_reason_order_return_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReturnRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_images', to='orders.orderitem')),
            ],
        ),
    ]
