# Generated by Django 6.0.7 on 2026-08-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_coupon_campaign_name_coupon_usage_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_first_order_only',
            field=models.BooleanField(default=False, help_text='Restricted to new users with 0 prior orders'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit_per_user',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Max redemptions per user', null=True),
        ),
    ]
