# Generated by Django 6.0.7 on 2026-08-31 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_category_discount_remove_category_expiry_date_and_more'),
        ('orders', '0017_orderitem_discount_amount'),
        ('products', '0007_product_brand_product_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='applicable_coupons', to='category.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='applicable_coupons', to='products.product'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='offer_type',
            field=models.CharField(choices=[('GENERAL', 'General Cart Offer'), ('CATEGORY_SPECIFIC', 'Category-Specific Offer'), ('PRODUCT_SPECIFIC', 'Product-Specific Offer'), ('REFERRAL', 'Referral Offer')], default='GENERAL', max_length=30),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Sign-up'), ('REGISTERED', 'Registered'), ('COMPLETED', 'First Purchase Completed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('reward_credited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('referred_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_by_relation', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
