# Generated by Django 6.0.7 on 2026-09-09 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_coupon_applicable_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referred_user',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referrer',
        ),
        migrations.RemoveField(
            model_name='returnrequestimage',
            name='order_item',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='ReturnRequestImage',
        ),
    ]
