# Generated by Django 6.0.7 on 2026-10-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_remove_referral_referred_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_PICKUP', 'Pickup Scheduled'), ('RETURNED', 'Returned'), ('RETURN_REJECTED', 'Return Rejected'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('PARTIALLY_RETURNED', 'Partially Returned')], default='CONFIRMED', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_PICKUP', 'Pickup Scheduled'), ('RETURNED', 'Returned'), ('RETURN_REJECTED', 'Return Rejected'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('PARTIALLY_RETURNED', 'Partially Returned')], default='CONFIRMED', max_length=50),
        ),
    ]
