# Generated by Django 5.2.4 on 2026-06-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='address_line_1',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='region_local',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='recipient_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='iso_region',
            new_name='state',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
